-- PEPE KUN Supabase setup. Run only if these tables do not already exist.
create table if not exists public.products (id bigint generated by default as identity primary key, name text not null, price numeric not null default 0, category text not null, tag text default '', image text default '', description text default '', specs jsonb default '[]'::jsonb, gallery jsonb default '[]'::jsonb, heightClass text default 'h-[300px]', created_at timestamptz default now());
create table if not exists public.carts (user_id uuid primary key references auth.users(id) on delete cascade, items jsonb not null default '[]'::jsonb, updated_at timestamptz default now());
create table if not exists public.orders (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null, items jsonb not null default '[]'::jsonb, order_total numeric not null default 0, status text not null default 'pending', shipping_details jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.enquiries (id bigint generated by default as identity primary key, name text not null, email text not null, message text not null, created_at timestamptz default now());
create unique index if not exists carts_user_id_key on public.carts(user_id);
alter table public.products enable row level security;
alter table public.carts enable row level security;
alter table public.orders enable row level security;
alter table public.enquiries enable row level security;
drop policy if exists products_public_read on public.products; create policy products_public_read on public.products for select using (true);
drop policy if exists products_admin_write on public.products; create policy products_admin_write on public.products for all to authenticated using (auth.jwt()->>'email'='admin@pepekun.com') with check (auth.jwt()->>'email'='admin@pepekun.com');
drop policy if exists carts_own on public.carts; create policy carts_own on public.carts for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists orders_own_read on public.orders; create policy orders_own_read on public.orders for select to authenticated using (auth.uid()=user_id or auth.jwt()->>'email'='admin@pepekun.com');
drop policy if exists orders_own_insert on public.orders; create policy orders_own_insert on public.orders for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists orders_admin_update on public.orders; create policy orders_admin_update on public.orders for update to authenticated using (auth.jwt()->>'email'='admin@pepekun.com') with check (auth.jwt()->>'email'='admin@pepekun.com');
drop policy if exists enquiries_public_insert on public.enquiries; create policy enquiries_public_insert on public.enquiries for insert to anon, authenticated with check (true);
drop policy if exists enquiries_admin_read on public.enquiries; create policy enquiries_admin_read on public.enquiries for select to authenticated using (auth.jwt()->>'email'='admin@pepekun.com');

-- Optional categories table for the Admin > Categories section.
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz default now()
);
alter table public.categories enable row level security;
drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select using (true);
drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories for all to authenticated
using (auth.jwt()->>'email'='admin@pepekun.com')
with check (auth.jwt()->>'email'='admin@pepekun.com');

-- Seed the three categories already used by the original PEPE KUN design.
insert into public.categories (name)
values ('Signature Collection'), ('Fantasy Series'), ('Mini Series')
on conflict (name) do nothing;
